<a href="https://colab.research.google.com/github/alejandroaviles/WL_MACSS-2023/blob/main/All_catallogs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
!git clone https://github.com/alejandroaviles/WL_MACSS-2023.git

Cloning into 'WL_MACSS-2023'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 174 (delta 16), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (174/174), 70.79 MiB | 16.33 MiB/s, done.
Resolving deltas: 100% (89/89), done.


In [31]:
pip install treecorr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [32]:
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
import os
import treecorr

In [33]:
os.chdir('WL_MACSS-2023')

In [34]:
def process_one(cosmostr,numbercat,size_in_degrees,minArcmin,maxArcmin,nbins):


    numberstr= str(numbercat)
    inputfile= 'gamma_'+cosmostr+'.'+numberstr+'.fits'
    outputfile= 'gamma_'+cosmostr+'.'+numberstr+'.txt'

    gammaFITS = fits.getdata(inputfile, ext=0)

    print('file:',inputfile)
    print('file shape is',gammaFITS.shape)
    length=gammaFITS.shape[0]

    gamma1 = np.zeros(length*length);
    gamma2 = np.zeros(length*length);
    yT = np.zeros(length*length);
    xT = np.zeros(length*length);

    tounits=size_in_degrees/length * np.pi/180; # 1 degree = pi/180

    nn=0;
    for jj in range(length):
        for ii in range(length):
            gamma1[nn] = gammaFITS[jj,ii,0]
            gamma2[nn] = gammaFITS[jj,ii,1]
            xT[nn] = ii*tounits
            yT[nn] = jj*tounits
            nn=nn+1

    minRad=minArcmin*np.pi/60/180
    maxRad=maxArcmin*np.pi/60/180
    #print("minRad={:.5}, maxRad={:.5}".format(minRad,maxRad))


    catalogue=treecorr.Catalog(x=xT,y=yT,g1=gamma1,g2=gamma2,x_units="rad",y_units="rad")
    GG=treecorr.GGCorrelation(min_sep=minRad,max_sep=maxRad,verbose=2,nbins=nbins)
    GG.process(catalogue)

    thtArr=np.array(GG.meanr)/np.pi*180*60

    # write all
    counter =0;
    saveto=outputfile
    print(saveto)
    header='1.theta[arcmin] 2.xiplus 3.ximinus 4.npairsinbin\n'
    with open(saveto, 'w') as file:
        file.write(header)
        for entry1, entry2, entry3, entry4 in zip(thtArr, GG.xip, GG.xim, GG.npairs):
            file.write(f"{entry1}\t{entry2}\t{entry3}\t{entry4}\n")
            counter +=1


    return thtArr, GG.xip, GG.xim, GG.npairs

In [35]:
for numbercat in range(4):
    process_one('A',numbercat,2,1,60,10)

file: gamma_A.0.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000354: sig_sn (per component) = 0.018827


INFO:treecorr:varg = 0.000354: sig_sn (per component) = 0.018827


gamma_A.0.txt
file: gamma_A.1.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000406: sig_sn (per component) = 0.020139


INFO:treecorr:varg = 0.000406: sig_sn (per component) = 0.020139


gamma_A.1.txt
file: gamma_A.2.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000519: sig_sn (per component) = 0.022777


INFO:treecorr:varg = 0.000519: sig_sn (per component) = 0.022777


gamma_A.2.txt
file: gamma_A.3.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000383: sig_sn (per component) = 0.019572


INFO:treecorr:varg = 0.000383: sig_sn (per component) = 0.019572


gamma_A.3.txt


In [36]:
process_one('B',0,2,1,60,10)

file: gamma_B.0.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000272: sig_sn (per component) = 0.016502


INFO:treecorr:varg = 0.000272: sig_sn (per component) = 0.016502


gamma_B.0.txt


(array([ 1.27790787,  1.91628783,  2.89006986,  4.3272716 ,  6.51742622,
         9.845097  , 14.83354816, 22.21270463, 33.38366049, 49.90964392]),
 array([2.19617209e-04, 1.59140036e-04, 1.10126986e-04, 7.71611441e-05,
        5.34265196e-05, 4.00535324e-05, 3.47262488e-05, 2.73819865e-05,
        1.26433175e-05, 1.97335867e-06]),
 array([-1.30020461e-06, -5.57604779e-07,  7.82823656e-07,  1.55251593e-07,
        -2.06026322e-07,  4.24280530e-07,  7.84852980e-07,  4.84431762e-07,
        -2.57896913e-06, -2.97713037e-06]),
 array([1.59999300e+08, 3.28748752e+08, 7.75693616e+08, 1.64243379e+09,
        3.79528320e+09, 8.26174438e+09, 1.76862413e+10, 3.57194220e+10,
        7.19928689e+10, 1.23286716e+11]))

In [37]:
process_one('B',9,2,1,60,10)

file: gamma_B.9.fits
file shape is (1024, 1024, 2)
nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


INFO:treecorr:nbins = 10, min,max sep = 0.000290888..0.0174533, bin_size = 0.409434


Starting process GG auto-correlations


INFO:treecorr:Starting process GG auto-correlations


Using 2 threads.


INFO:treecorr:Using 2 threads.


Building GField


INFO:treecorr:Building GField


Starting 256 jobs.


INFO:treecorr:Starting 256 jobs.


varg = 0.000242: sig_sn (per component) = 0.015572


INFO:treecorr:varg = 0.000242: sig_sn (per component) = 0.015572


gamma_B.9.txt


(array([ 1.27790787,  1.91628783,  2.89006986,  4.3272716 ,  6.51742622,
         9.845097  , 14.83354816, 22.21270463, 33.38366049, 49.90964392]),
 array([1.84880444e-04, 1.30828777e-04, 8.74204603e-05, 5.71287972e-05,
        3.77433547e-05, 2.68551162e-05, 1.48712716e-05, 9.44287397e-06,
        5.66122702e-06, 3.69687173e-06]),
 array([-9.98002000e-08, -8.30426461e-07,  8.59304733e-07, -1.47980443e-06,
         6.95621774e-07,  4.97048720e-07, -5.48542353e-08, -3.34122901e-06,
        -6.31746025e-07,  5.25990847e-07]),
 array([1.59999300e+08, 3.28748752e+08, 7.75693616e+08, 1.64243379e+09,
        3.79528320e+09, 8.26174438e+09, 1.76862413e+10, 3.57194220e+10,
        7.19928689e+10, 1.23286716e+11]))